### ISSUE TITLE
Impossible to run tests

### ISSUE THREAD

**Issue by MikeAski** [minifeed/iridium#31]
When running `iridium test`, I get the following message:

```
  Tasks:
  iridium test_command help [COMMAND]  # Describe subcommands or one specific subcommand
  iridium test_command test PATHS      # run tests match by PATHS
```

which is a quite strange content (what is this `test_command` expected token?).

When I try `iridium test test`, I get:

```
/home/mike/.rvm/gems/ruby-1.9.3-p125/bundler/gems/thor-15eedc90f499/lib/thor/core_ext/hash_with_indifferent_access.rb:26:in `[]=': can't modify frozen Thor::CoreExt::HashWithIndifferentAccess (RuntimeError)
    from /home/mike/.rvm/gems/ruby-1.9.3-p125/bundler/gems/thor-15eedc90f499/lib/thor/core_ext/hash_with_indifferent_access.rb:26:in `[]='
    from /home/mike/.rvm/gems/ruby-1.9.3-p125/bundler/gems/iridium-7396999d5753/lib/iridium/testing/suite.rb:99:in `execute'
    from /home/mike/.rvm/gems/ruby-1.9.3-p125/bundler/gems/iridium-7396999d5753/lib/iridium/testing/test_command.rb:18:in `test'
    from /home/mike/.rvm/gems/ruby-1.9.3-p125/bundler/gems/thor-15eedc90f499/lib/thor/task.rb:27:in `run'
    from /home/mike/.rvm/gems/ruby-1.9.3-p125/bundler/gems/thor-15eedc90f499/lib/thor/invocation.rb:120:in `invoke_task'
    from /home/mike/.rvm/gems/ruby-1.9.3-p125/bundler/gems/thor-15eedc90f499/lib/thor.rb:344:in `dispatch'
    from /home/mike/.rvm/gems/ruby-1.9.3-p125/bundler/gems/thor-15eedc90f499/lib/thor/invocation.rb:109:in `invoke'
    from /home/mike/.rvm/gems/ruby-1.9.3-p125/bundler/gems/thor-15eedc90f499/lib/thor.rb:214:in `block in subcommand'
    from /home/mike/.rvm/gems/ruby-1.9.3-p125/bundler/gems/thor-15eedc90f499/lib/thor/task.rb:27:in `run'
    from /home/mike/.rvm/gems/ruby-1.9.3-p125/bundler/gems/thor-15eedc90f499/lib/thor/invocation.rb:120:in `invoke_task'
    from /home/mike/.rvm/gems/ruby-1.9.3-p125/bundler/gems/thor-15eedc90f499/lib/thor.rb:344:in `dispatch'
    from /home/mike/.rvm/gems/ruby-1.9.3-p125/bundler/gems/thor-15eedc90f499/lib/thor/base.rb:434:in `start'
    from /home/mike/.rvm/gems/ruby-1.9.3-p125/bundler/gems/iridium-7396999d5753/bin/iridium:4:in `<top (required)>'
    from ../bin/iridium:16:in `load'
    from ../bin/iridium:16:in `<main>'
```

So it seems `testing/suite.rb` has incorrect action at line 99...

The project was generated using `iridium generate app`.

**Comment by ahawkins** [comment]
K. I'll fix this tonight

**Comment by ahawkins** [comment]
@MikeAski I also need to look into issue with thor that requires you to run `iridium test test`. `test` is the default task on the `test` command.

**Comment by ahawkins** [comment]
fixed.

**Comment by MikeAski** [comment]
Thx a lot. Thx also for your reactivity :+1:
